title: Scrap Mechanic Modding Tutorials
author: Fagiano0
description: > 
  Welcome to SMMT!
  Here you will find tutorials and guides to Scrap Mechanic modding.
remote_theme: abhinavs/moonwalk

favicon: "./favicon.ico"

theme_config:
  appearance: "dark"
  appearance_toggle: true
  show_description: true